name: 'Check Pull Request OCAs'
author: 'amine-arb-2019'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  pull-request-number:
    description: 'The Pull Request number'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.pull-request-number }}
